import Advertisement from '@/components/organism/advertisement/Advertisement'
import BannerCard from '@/components/molecules/card/BannerCard'
import PostCard from '@/components/molecules/card/PostCard'
import Link from 'next/link'
import BlogListing from './blog/page'

export const metadata = {
   title: 'Home Page | Gamigin',
   description: 'Generated by create next app',
}
export default function Home() {
   return (
      <main className="container mx-auto">
         {/* Banner Component */}
         
         <BlogListing/>
      </main>
   )
}
